### ISSUE TITLE
大佬是转做Java了嘛？

### ISSUE THREAD

**Issue by xiaobao996** [ResolveWang/maven-in-action#1]

**Comment by ResolveWang** [comment]
之后工作内容是做中间件开发，技术栈大概是Java+Go

**Comment by JieZhaoAllen** [comment]
之前看您项目都是Python的 ，是因为不看好Python就业前景才做Java嘛？

**Comment by ResolveWang** [comment]
不是啊，学什么是项目需求，我现在还在实验室给导师做项目，基本是做舆情分析相关的，因此用的Python比较多，校招面试简历上我也是写的熟悉Python，没写Java。拿了一些Offer有一大半是做Python相关的开发，有一些是Java相关的。一般来说大一点的公司都愿意培养新人，因此语言不是决定性因素，主要还是看你的基础知识，比如我就比较熟悉计算机网络和数据库方面的知识。
